version: 2

project_name: forq

before:
  hooks:
    - go mod tidy

builds:
  - id: forq
    binary: forq
    main: ./
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: forq
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

dockers:
  - id: forq-amd64
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/forq:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/forq:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
    extra_files:
      - db/migrations
      - ui/templates
    goos: linux
    goarch: amd64
  - id: forq-arm64
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/forq:{{ .Version }}-arm64"
      - "{{ .Env.DOCKER_USERNAME }}/forq:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --pull
    extra_files:
      - db/migrations
      - ui/templates
    goos: linux
    goarch: arm64

docker_manifests:
  - name_template: "{{ .Env.DOCKER_USERNAME }}/forq:{{ .Version }}"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/forq:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/forq:{{ .Version }}-arm64"
  - name_template: "{{ .Env.DOCKER_USERNAME }}/forq:latest"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/forq:latest-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/forq:latest-arm64"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: n0rdy  # Change this to your GitHub username
    name: forq
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Forq {{ .Tag }}

    **Full Changelog**: https://github.com/n0rdy/forq/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    **Binary releases (Linux only):**
    ```bash
    # Download for your architecture from the assets below
    # Example for Linux x86_64:
    curl -L https://github.com/n0rdy/forq/releases/download/{{ .Tag }}/forq_Linux_x86_64.tar.gz | tar -xz
    chmod +x forq && sudo mv forq /usr/local/bin/

    # Example for Linux ARM64:
    curl -L https://github.com/n0rdy/forq/releases/download/{{ .Tag }}/forq_Linux_arm64.tar.gz | tar -xz
    chmod +x forq && sudo mv forq /usr/local/bin/
    ```

    **Other platforms:**
    ```bash
    # macOS/Windows users can build from source or use Docker
    git clone https://github.com/n0rdy/forq && cd forq && go build
    ```

    **Docker:**
    ```bash
    docker run -d \
      --name forq \
      --restart unless-stopped \
      -e FORQ_AUTH_SECRET=your-auth-secret-min-32-chars-long \
      -e FORQ_DB_PATH=/app/data/forq/forq.db \
      -e FORQ_API_ADDR=0.0.0.0:8080 \
      -e FORQ_UI_ADDR=0.0.0.0:8081 \
      -p 8080:8080 \
      -p 8081:8081 \
      -v ~/forq-data:/app/data/forq \
      {{ .Env.DOCKER_USERNAME }}/forq:{{ .Tag }}
    ```
