############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Documentation"
url = "/documentation-portal/docs/guides/getting-started/"
weight = 2

# footer menu
