package ui

import "embed"

//go:embed templates/*.html
var templatesFS embed.FS

// staticFS holds the precompiled UI assets (Tailwind+DaisyUI CSS, HTMX, theme
// script). They are generated by `npm run build` in ui/ and checked into the
// repo, so the binary is fully self-contained and the admin UI works offline.
//
//go:embed static
var staticFS embed.FS
