name: Release

on:
  push:
    tags: ['v*']
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Install SQLite development headers
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

    - name: Test GoReleaser config
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: check

    - name: Test build (snapshot)
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: build --snapshot --clean
  
  build-amd64:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Install SQLite development headers
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

    - name: Build AMD64
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: build --single-target --snapshot --clean
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Upload AMD64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-amd64
        path: dist/

  build-arm64:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Install SQLite development headers
      run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

    - name: Build ARM64
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: build --single-target --snapshot --clean
      env:
        GOOS: linux
        GOARCH: arm64

    - name: Upload ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-arm64
        path: dist/

  release:
    if: github.event_name != 'pull_request'
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
        cache: true

    - name: Download AMD64 artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-amd64
        path: dist/

    - name: Download ARM64 artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-arm64
        path: dist/
        merge-multiple: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Release with pre-built binaries
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --skip=before
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
